"""empty message

Revision ID: 938cc0f27b6a
Revises: c97ba03ddb4c
Create Date: 2019-06-03 16:16:32.497831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938cc0f27b6a'
down_revision = 'c97ba03ddb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
